### PR TITLE
[93-travis-update] changed yml file per nancy

### PR DESCRIPTION
**Pull request by CatherineRH**

### CODE REVIEW

**Comment by CatherineRH** [comment]
@evpoe @beafus  @sa3613  @cambriaso both of these checks have passed now based on edits to Travis YML file based on Nancy and Kelly's suggested edits to the folow of operations. Could someone take a look and merge?

**Comment by CatherineRH** [comment]
@beafus I left the port for the database URI the same, since that's what kelly still had

**Comment by evpoe** [comment]
@CatherineRH what exact issue is this addressing? is this one you and bea came across when building out the toolchain?

**Comment by CatherineRH** [comment]
@evpoe this is related to issue #2 in the slack channel, where when we run tests in the build stage, we get the error that says that the server can't be reached. per Kelly's convo with Nancy, that's because the travis YML file from the demo was not set up well and required re-organization. Just tagged you into the slack thread

**Comment by evpoe** [comment]
Looks good and passes all tests

**Pull request merged**
